language: python
python:
  - 2.7
before_install:
  # Hack to workaround https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - echo Preinstalled
  - pip freeze
  - sudo apt-get build-dep -qq python-scipy python-pandas cython
  # Need something like scipy 0.10, pandas 0.12, not sure about cython (want memoryview support anyway, 0.15 does NOT work, 0.19 does)
  - pip install --use-mirrors --upgrade coverage scipy cython patsy pandas
  - echo Final installation
  - pip freeze
  - which nosetests
  - python -c 'import numpy; print(numpy.__version__)'
install:
  - python setup.py install
script:
  # We change directories to make sure that python won't find the copy
  # of the package inside the source directory.
  - export PYRERP_TEST_DATA=$PWD/test-data
  - mkdir empty
  - cd empty
  - INSTALLDIR=$(python -c "import os; import pyrerp; print(os.path.dirname(pyrerp.__file__))")
  - export PYTHONWARNINGS=default PYRERP_FORCE_NO_WARNINGS=1
  # The --exe is because python sometimes marks all installed modules
  # as executable, so without --exe nosetests will just ignore
  # everything. Baffling, but so it goes.
  - coverage run --source=$INSTALLDIR --rcfile=../.coveragerc $(which nosetests) --exe --failure-detail --all-modules $INSTALLDIR
  - coverage report --rcfile=../.coveragerc --show-missing
notifications:
  email:
    - njs@pobox.com
after_success:
  - pip install --use-mirrors coveralls && coveralls
